import { useEffect, useState } from "react";
import { FiImage, FiSave, FiTrash2, FiUpload } from "react-icons/fi";
import bagongPilipinasLogo from "../assets/Bagong_Pilipinas_Logo.png";
import { apiUrl } from "../lib/api";
import "../styles/settings.css";

export default function Customization() {
  const [logo, setLogo] = useState(""); const [file, setFile] = useState(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch(apiUrl("/api/barangays/profile"), { headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } }).then((response) => response.json()).then((data) => setLogo(data.profile?.logo_url || "")); }, []);
  function choose(event) { const selected = event.target.files?.[0]; if (!selected) return; if (!selected.type.startsWith("image/")) return setMessage("Choose a valid image file."); setFile(selected); setLogo(URL.createObjectURL(selected)); setMessage("Logo selected. Save to share it across devices."); }
  async function save() { setSaving(true); try { const body = new FormData(); if (file) body.append("logo", file); if (!logo) body.append("removeLogo", "true"); const response = await fetch(apiUrl("/api/barangays/profile"), { method: "PUT", headers: { Authorization: `Bearer ${localStorage.getItem("token")}` }, body }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setLogo(data.profile.logo_url || ""); setFile(null); setMessage("Customization saved for all devices."); } catch (error) { setMessage(error.message); } finally { setSaving(false); } }
  return <main className="account-settings-page"><header><span>BRANDING</span><h1>Customization</h1><p>Manage the barangay logo used in BPS and certificate headers.</p></header>{message && <div className="profile-message">{message}</div>}<div className="customization-grid"><section className="account-settings-card"><h2>Barangay logo</h2><p>Use a clear square PNG or JPG. This shared logo appears on all devices.</p><label className="custom-logo-dropzone">{logo ? <img src={logo} alt="Barangay logo preview" /> : <span><FiImage />Upload barangay logo</span>}<input type="file" accept="image/*" onChange={choose} /></label><div className="customization-actions"><label><FiUpload />Choose image<input type="file" accept="image/*" onChange={choose} /></label><button type="button" onClick={() => { setLogo(""); setFile(null); }} disabled={!logo}><FiTrash2 />Remove</button><button type="button" onClick={save} disabled={saving || (!file && logo)}><FiSave />{saving ? "Saving..." : "Save customization"}</button></div></section><section className="account-settings-card"><h2>Certificate header preview</h2><p>Preview the shared logo used in certificate headers.</p><div className="certificate-header-preview"><img src={bagongPilipinasLogo} alt="Bagong Pilipinas logo" /><div><p>Republic of the Philippines</p><p>Province / Municipality</p><h3>Barangay Name</h3><span>Office of the Punong Barangay</span></div>{logo ? <img src={logo} alt="Barangay logo" /> : <div className="preview-logo-placeholder">Barangay Logo</div>}</div></section></div></main>;
}
